version: '3.8'

services:
  price-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - LIQUIDITY_PARAMETER=100
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3